trigger:
  branches:
    include:
    - '*' # must quote since "*" is a YAML reserved character; we want a string
  paths:
    exclude:
    - '*.md'

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk'
  inputs:
    packageType: sdk
    version: 8.0.x

- task: UseDotNet@2
  displayName: 'Use .NET 9 sdk'
  inputs:
    packageType: sdk
    version: 9.0.x

- script: dotnet --info
  displayName: 'dotnet info'

- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    Nuget__ApiKey: $(nugetApiKey)
    Nuget__SourceUrl: $(nugetSourceUrl)
