<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WeihanLi.Npoi\WeihanLi.Npoi.csproj" />
    <Using Include="WeihanLi.Npoi" />
    <Using Include="WeihanLi.Npoi.Attributes" />
  </ItemGroup>
</Project>
