name: dotnet-format-validation

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
            10.0.x
    - name: build
      run: dotnet build
    - name: check format
      run: dotnet format --verify-no-changes
