name: default

on: [push, pull_request]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    - name: dotnet info
      run: dotnet --info
    - name: build
      run: bash build.sh --target=build
  
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    - name: dotnet info
      run: dotnet --info
    - name: build
      run: bash build.sh --target=build
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.0
      with:
        binary-path: './src/WeihanLi.Npoi/bin/Release/netstandard2.0'
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
      
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    - name: dotnet info
      run: dotnet --info
    - name: build
      shell: pwsh
      run: .\build.ps1
