name: Release
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      shell: pwsh
      run: .\build.ps1 --stable=true
    - name: Get Release Version
      shell: pwsh
      run: .\build\getReleaseVersion.ps1
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.ReleaseVersion }}
        title: ${{ env.ReleaseVersion }}
        prerelease: false
        files: |
          artifacts/packages/*
